# Generated by Django 6.0 on 2025-12-08 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('market_fee', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PriceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.market')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produce')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('volume_sold', models.FloatField()),
                ('actual_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('market_sold_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.market')),
                ('produce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.produce')),
            ],
        ),
    ]
