# Generated by Django 6.0 on 2025-12-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricelog',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='salesrecord',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='pricelog',
            index=models.Index(fields=['date', 'produce'], name='api_pricelo_date_4116d4_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelog',
            index=models.Index(fields=['market', 'produce'], name='api_pricelo_market__3fe5d6_idx'),
        ),
    ]
